-- +goose Up
CREATE TABLE Tweets(
id UUID PRIMARY KEY,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
body TEXT NOT NULL,
user_id UUID,
 CONSTRAINT user_id 
      FOREIGN KEY(id)
        REFERENCES users(id )
        ON DELETE CASCADE 
);
-- +goose Down
DROP  TABLE Tweets;
